### ISSUE TITLE
ERROR: Class file for report "ObliviousHarmony\VSCodePHPCSIntegration\VSCodeIntegration" not found

### ISSUE THREAD

**Issue by Eitan-brightleaf** [ObliviousHarmony/vscode-php-codesniffer#101]
### Description

I just installed the extension today. At first it was working but than I started getting this error message: `ERROR: Class file for report "ObliviousHarmony\VSCodePHPCSIntegration\VSCodeIntegration" not found` every time I open a file and after that nothing happens. I'm not sure if I configured something wrong or not...

Thanks in advance

**Comment by ObliviousHarmony** [comment]
No worries!

**Comment by tbradsha** [comment]
I also noticed this error when playing with settings. Sounds like it's a non-issue, but I'd recommend having the error point people to the documentation so they know it's expected.
