### ISSUE TITLE
Gets hung and stops working.

### ISSUE THREAD

**Issue by rubberneck** [ObliviousHarmony/vscode-php-codesniffer#31]
### Description

This will just stop working / get hung after a while at the bottom it will show a spinning wheel and say `PHP_Codesniffer Processing 11 Documents...` The number that it shows will change when i open and close documents but it's not correct. When it was showing 11 I only had 8 files open actually open.

### Other Info
This is using the snap version of vscode on Ubuntu 20.04 with phpcs installed globally in the path with composer. 

In the console there wasn't anything in `OUTPUT` for the `PHP_Codesniffer` selection. There were some errors in the `Log (Extension Host)` but they were all `intelephense` ones I didn't see anything for `PHP_Codesniffer`

Please forgive me as I don't know how or where to collect logs or any other useful information about this. If you can point me in the right direction and can collect all of the logs when it happens again.

Closing vscode and reopening it will be running fine again.

**Comment by ObliviousHarmony** [comment]
Thanks @rubberneck, this report is fine 😄.

In addition to looking for cases where a worker may stall, I'll add a cancel button to the notification area that stops all processing entirely to remove the need to restart if anything like this goes wrong in the future.

**Comment by ObliviousHarmony** [comment]
Hey @rubberneck,

The latest version of the extension, 1.4.0, contains a new command that you can use to cancel all of the extension's processing. Let me know how that works out for you!
