### ISSUE TITLE
Option to run only on save

### ISSUE THREAD

**Issue by johnbillion** [ObliviousHarmony/vscode-php-codesniffer#32]
First of all thanks for this extension. I know that maintaining these sorts of tools can be a thankless task.

### Problem Description

When I'm in the middle of writing code I find the code sniffing warnings to be a distraction. If I pause for a moment I don't want my editor telling me I'm a terrible programmer before I've had the chance to fix the formatting.

### Proposed Solution

It would be great if there was an option to only trigger the code sniffing when the file is saved. I currently use [shevaua/vscode-phpcs](https://github.com/shevaua/vscode-phpcs/) which provides this feature via its `lintOnType`, `lintOnOpen`, and `lintOnSave` options.

Cheers!

**Comment by ObliviousHarmony** [comment]
Thanks @johnbillion,

Sure, this is easy enough 😄

**Comment by ObliviousHarmony** [comment]
For this feature @johnbillion, what is the behaviour when you start typing again? Are the diagnostics cleared until you trigger the linter again manually? Technically the character positions are associated with the diagnostics, so once you change the content of the code, there's a good chance they aren't really useful anymore?

**Comment by johnbillion** [comment]
I'm not 100% sure but I think VS Code automatically adjusts the position of decorations when you subsequently modify the code. Here's a short screencast of the behaviour with shevaua/vscode-phpcs:

https://user-images.githubusercontent.com/208434/127659682-98a019a6-887c-43c8-83ad-a993923c1cb7.mp4

**Comment by ObliviousHarmony** [comment]
Hey @johnbillion,

The latest 1.4.0 version of the extension now includes this feature. Please let me know how it works out!
