### ISSUE TITLE
Help with installation instructions.

### ISSUE THREAD

**Issue by justageek** [ObliviousHarmony/vscode-php-codesniffer#36]
Hi, can you provide installation instructions for your plugin, I am using the old version of vscode-phpcs which is causing me huge headaches taking all my cpu, for some reason when I switch git branches it starts sniffing every file in the repo.

**Comment by ObliviousHarmony** [comment]
Hello @justageek,

You can install it [using the Visual Studio Marketplace item](https://marketplace.visualstudio.com/items?itemName=obliviousharmony.vscode-php-codesniffer). Once you've installed it, simply configure the `phpCodeSniffer` options, specifically the `Standard` and `Executable` settings, as well as any of the others that you're interested in.
