### ISSUE TITLE
Automatic standard detection

### ISSUE THREAD

**Issue by sirbrillig** [ObliviousHarmony/vscode-php-codesniffer#4]
### Problem Description

Many projects have a phpcs config file, which also counts as a Standard (when running phpcs you can specify a config file with the `--standard` option and it will use the standards listed in that file). Rather than having to configure the plugin to a single Standard, it would be nice to have an option to automatically search for [the nearest config file](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#using-a-default-configuration-file) and use that as the standard as phpcs itself does (alternatively, allow phpcs to detect the file itself).

**Comment by ObliviousHarmony** [comment]
Greetings @sirbrillig,

This has been taken care of in #2 and released just now in v0.3.0!
