### ISSUE TITLE
Add a link to the VS Code Marketplace

### ISSUE THREAD

**Issue by johnbillion** [ObliviousHarmony/vscode-php-codesniffer#40]
From the GitHub repo there's no link to the VS Code Marketplace anywhere. Would be good to put it in the repo sidebar, in the readme, etc.

**Comment by ObliviousHarmony** [comment]
I avoided adding it to the readme since that gets published as part of the package to the marketplace. I've gone ahead and added it to the sidebar though. Thanks for the suggestion!
