### ISSUE TITLE
Auto fix errors on save

### ISSUE THREAD

**Issue by khromov** [ObliviousHarmony/vscode-php-codesniffer#41]
Thank you for this extension, it works great and I appreciate that it's smart enough to look in the parent folder of the file being edited to find `phpcs`.

### Problem Description

Although I see errors and can fix them one by one via the VSCode submenu, I'd like to automatically run fix when I save the file. 

### Proposed Solution

An option similar to ESLints `source.fixAll.eslint`

**Comment by khromov** [comment]
@ObliviousHarmony Thank you, that worked perfectly! You can open the VSCode command palette, type `> Format document with` and select "Configure default formatter" to switch to PHP_CodeSniffer easily. 🚀

**Comment by yCodeTech** [comment]
I'd suggest you update the docs to include this information, because it's not so obvious.
