### ISSUE TITLE
Provide plugin on open-vsx.org

### ISSUE THREAD

**Issue by tm1000** [ObliviousHarmony/vscode-php-codesniffer#43]
See: https://github.com/VSCodium/vscodium/blob/master/DOCS.md?rgh-link-date=2021-01-28T08%3A31%3A00Z#extensions-marketplace

Once you provide the plugin here it can be used on https://github.com/coder/code-server

**Comment by ObliviousHarmony** [comment]
Sorry for the wait, [I've published the extension](https://open-vsx.org/extension/obliviousharmony/vscode-php-codesniffer).

**Comment by tm1000** [comment]
@ObliviousHarmony Thank you!!!
