### ISSUE TITLE
The PHPCS worker encountered an error: `env: php: No such file or directory`

### ISSUE THREAD

**Issue by danielpost** [ObliviousHarmony/vscode-php-codesniffer#54]
### Description

I'm not sure if this is something in my local config, but I'm suddenly getting the following error: `The PHPCS worker encountered an error.`. When checking the extension output, it says `env: php: No such file or directory`.

I've tried a couple things:

```
$ php -v
PHP 8.0.25 (cli) (built: Nov  3 2022 09:27:45) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.25, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.25, Copyright (c), by Zend Technologies
```

```
$ which php
/opt/homebrew/bin/php
```

I also tried setting `"php.debug.executablePath": "/opt/homebrew/bin/php"` in `settings.json` but that didn't work either.

### Reproduction Steps

1. Open a PHP file in VS Code.
2. See the error.

### Expected Behavior

PHPCS would work as expected without the error.

<img width="565" alt="Screenshot 2022-11-10 at 13 28 25@2x" src="https://user-images.githubusercontent.com/1713699/201091716-b2a7516b-3ec9-4381-be7a-4cc9a09aa498.png">

<img width="703" alt="Screenshot 2022-11-10 at 13 28 31@2x" src="https://user-images.githubusercontent.com/1713699/201091727-00e78aba-81b1-4e24-b093-f844a8d5a291.png">

**Comment by danielpost** [comment]
Some updates on my local config seem to have fixed it, sorry for the noise!

**Comment by ObliviousHarmony** [comment]
Thanks @danielpost, I'm glad to have helped by procrastinating! The joys of parental leave and being a new parent 😃

Have a good week!
